import type { Substep } from '../types';
import { word, nonsense } from '../build';

export const SUBSTEP_2_4: Substep = {
  id: '2.4',
  title: 'Five sounds in a word',
  parentSummary:
    'Your child taps words with five sounds, a blend at the start and another consonant or two at the end, such as "spend" and "crisp". The rule has not changed: just count the sounds and tap one at a time before you swipe to blend them.',
  groups: [
    {
      cards: [],
      lesson: [
        { say: 'Longer words are still just sounds. More sounds simply means more taps before you swipe.' },
        { show: ['s', 'p', 'e', 'n', 'd'] },
        { say: 'Five sounds, five taps: s, p, e, n, d, then swipe to blend them into spend.' },
        { tap: 'spend' },
        { say: 'Your turn. Tap every sound in order, then swipe to say the word.' },
        { try: 'plant' },
        { try: 'crisp' },
        { try: 'trust' },
      ],
    },
  ],
  concepts: [],
  sightWords: ['put', 'saw', 'want', 'again'],
  words: [
    // Five-sound words: a blend at the start, one or two consonants at the end.
    word('spend', 's,p,e,n,d'),
    word('blend', 'b,l,e,n,d'),
    word('blimp', 'b,l,i,m,p'),
    word('blond', 'b,l,o,n,d'),
    word('brand', 'b,r,a,n,d'),
    word('clamp', 'c,l,a,m,p'),
    word('cramp', 'c,r,a,m,p'),
    word('crisp', 'c,r,i,s,p'),
    word('crust', 'c,r,u,s,t'),
    word('draft', 'd,r,a,f,t'),
    word('drift', 'd,r,i,f,t'),
    word('frost', 'f,r,o,s,t'),
    word('grand', 'g,r,a,n,d'),
    word('grant', 'g,r,a,n,t'),
    word('grasp', 'g,r,a,s,p'),
    word('plant', 'p,l,a,n,t'),
    word('print', 'p,r,i,n,t'),
    word('slept', 's,l,e,p,t'),
    word('spent', 's,p,e,n,t'),
    word('stamp', 's,t,a,m,p'),
    word('stump', 's,t,u,m,p'),
    word('swift', 's,w,i,f,t'),
    word('trust', 't,r,u,s,t'),
    word('twist', 't,w,i,s,t'),
    word('thrift', 'th,r,i,f,t'),
    // A blend plus a final digraph.
    word('crunch', 'c,r,u,n,ch'),
    word('trench', 't,r,e,n,ch'),
    word('drench', 'd,r,e,n,ch'),
    word('clench', 'c,l,e,n,ch'),
    word('flinch', 'f,l,i,n,ch'),

    // Nonsense: the same five-sound shape.
    nonsense('blimt', 'b,l,i,m,t'),
    nonsense('drist', 'd,r,i,s,t'),
    nonsense('flomp', 'f,l,o,m,p'),
    nonsense('plisk', 'p,l,i,s,k'),
    nonsense('stend', 's,t,e,n,d'),
    nonsense('brulp', 'b,r,u,l,p'),
    nonsense('frisp', 'f,r,i,s,p'),
    nonsense('swelt', 's,w,e,l,t'),
    nonsense('grelp', 'g,r,e,l,p'),
    nonsense('clesp', 'c,l,e,s,p'),
    nonsense('plunt', 'p,l,u,n,t'),
    nonsense('swimp', 's,w,i,m,p'),
  ],
  sentences: [
    'Sam has a crisp chip.',
    'The hen sat on the stump.',
    'Dan can plant a yam.',
    'Jan does not trust the fox.',
    'The kid can twist and hop.',
    'The cat slept on the mat.',
    'Sam and Pam plant a fig.',
    'The duck has a swift kick.',
    'The fox can crunch a chip.',
    'Sam put the chip in a pan.',
    'Dan saw a duck on the stump.',
    'Sam and Jan want to run again.',
  ],
  stories: [
    {
      title: 'The Crisp Chip on the Hill',
      sentences: [
        'Sam and Jan run up the hill.',
        'Frost is on the moss and the rock.',
        'Sam and Jan want a crisp chip.',
        'Jan has the crisp chip.',
        'Sam does not have a chip.',
        'The crisp chip is for Sam and Jan.',
        'Sam and Jan sit on the rock.',
      ],
      questions: [
        { prompt: 'What is on the moss?', choices: ['frost', 'the sun', 'a chip'], answer: 0 },
        { prompt: 'Who has the crisp chip at the start?', choices: ['Jan', 'Sam', 'the hill'], answer: 0 },
      ],
    },
    {
      title: 'Dan and the Stump',
      sentences: [
        'Dan is on a big stump.',
        'A duck is at the stump.',
        'Dan and the duck sit on the stump.',
        'The duck has a print in the mud.',
        'Dan does not have a print.',
        'Dan and the duck stamp in the mud.',
      ],
      questions: [
        { prompt: 'Where does Dan sit?', choices: ['on a stump', 'in the mud', 'on a rock'], answer: 0 },
        { prompt: 'What does the duck have?', choices: ['a print', 'a chip', 'a stump'], answer: 0 },
      ],
    },
  ],
};
