import type { Substep } from '../types';
import { word, nonsense } from '../build';

export const SUBSTEP_3_2: Substep = {
  id: '3.2',
  title: 'Two syllables with blends',
  parentSummary:
    'Your child reads two-syllable words made of two closed syllables, where at least one syllable has a blend, two or more consonants said together, such as "problem" and "pumpkin". They keep tapping every sound in order, syllable by syllable, then swipe to blend each part and say the whole word.',
  groups: [
    {
      cards: [],
      lesson: [
        { say: 'Today some syllables have a blend too, two or more sounds squeezed together, and we still tap every sound.' },
        { show: ['p', 'r', 'o', 'b', 'l', 'e', 'm'] },
        { say: 'Problem has two syllables, prob and lem. The first syllable starts with the blend p and r together.' },
        { tap: 'problem' },
        { say: 'Your turn. Tap every sound in each syllable, then swipe to blend the whole word.' },
        { try: 'blanket' },
        { try: 'pumpkin' },
        { try: 'unplug' },
      ],
    },
  ],
  concepts: [],
  sightWords: ['little', 'over', 'only', 'other'],
  words: [
    // Real: two closed syllables, at least one with a blend
    word('problem', 'p,r,o,b,l,e,m', { syllables: [4] }),
    word('plastic', 'p,l,a,s,t,i,c', { syllables: [4] }),
    word('dentist', 'd,e,n,t,i,s,t', { syllables: [3] }),
    word('contest', 'c,o,n,t,e,s,t', { syllables: [3] }),
    word('children', 'ch,i,l,d,r,e,n', { syllables: [3] }),
    word('hundred', 'h,u,n,d,r,e,d', { syllables: [3] }),
    word('blanket', 'b,l,a,n,k,e,t', { syllables: [4] }),
    word('trumpet', 't,r,u,m,p,e,t', { syllables: [4] }),
    word('pumpkin', 'p,u,m,p,k,i,n', { syllables: [4] }),

    word('address', 'a,d,d,r,e,ss:s', { syllables: [2] }),
    word('unplug', 'u,n,p,l,u,g', { syllables: [2] }),
    word('command', 'c,o,m,m,a,n,d', { syllables: [3] }),
    word('invent', 'i,n,v,e,n,t', { syllables: [2] }),
    word('sandwich', 's,a,n,d,w,i,ch', { syllables: [4] }),
    word('bandit', 'b,a,n,d,i,t', { syllables: [4] }),
    word('handstand', 'h,a,n,d,s,t,a,n,d', { syllables: [4] }),
    word('frantic', 'f,r,a,n,t,i,c', { syllables: [4] }),
    word('splendid', 's,p,l,e,n,d,i,d', { syllables: [5] }),
    word('pretzel', 'p,r,e,t,z,e,l', { syllables: [4] }),
    word('instant', 'i,n,s,t,a,n,t', { syllables: [2] }),
    word('expand', 'e,x,p,a,n,d', { syllables: [2] }),
    word('impress', 'i,m,p,r,e,ss:s', { syllables: [2] }),
    word('handoff', 'h,a,n,d,o,ff:f', { syllables: [4] }),
    word('windmill', 'w,i,n,d,m,i,ll:l', { syllables: [4] }),
    word('sandbox', 's,a,n,d,b,o,x', { syllables: [4] }),
    word('extend', 'e,x,t,e,n,d', { syllables: [2] }),

    word('softball', 's,o,f,t,b,all', { syllables: [4] }),

    // More real words in the same shape, added so the section has enough to read.
    word('sunblock', 's,u,n,b,l,o,ck', { syllables: [3] }),
    word('drumstick', 'd,r,u,m,s,t,i,ck', { syllables: [4] }),
    word('compost', 'c,o,m,p,o,s,t', { syllables: [3] }),
    word('lipstick', 'l,i,p,s,t,i,ck', { syllables: [3] }),
    word('kickstand', 'k,i,ck,s,t,a,n,d', { syllables: [3] }),
    word('windsock', 'w,i,n,d,s,o,ck', { syllables: [4] }),
    word('lunchbox', 'l,u,n,ch,b,o,x', { syllables: [4] }),
    word('backdrop', 'b,a,ck,d,r,o,p', { syllables: [3] }),

    // Nonsense: same two-closed-syllable shape, always with a blend
    nonsense('blastin', 'b,l,a,s,t,i,n'),
    nonsense('crimpet', 'c,r,i,m,p,e,t'),
    nonsense('dranlop', 'd,r,a,n,l,o,p'),
    nonsense('flistub', 'f,l,i,s,t,u,b'),
    nonsense('grendit', 'g,r,e,n,d,i,t'),
    nonsense('plomkin', 'p,l,o,m,k,i,n'),
    nonsense('scaltop', 's,c,a,l,t,o,p'),
    nonsense('trubmit', 't,r,u,b,m,i,t'),
    nonsense('vindrest', 'v,i,n,d,r,e,s,t'),
    nonsense('wispram', 'w,i,s,p,r,am'),
    nonsense('stubnet', 's,t,u,b,n,e,t'),
    nonsense('clundip', 'c,l,u,n,d,i,p'),
    nonsense('brantip', 'b,r,a,n,t,i,p'),
    nonsense('clempot', 'c,l,e,m,p,o,t'),
    nonsense('drenlip', 'd,r,e,n,l,i,p'),
    nonsense('flampet', 'f,l,a,m,p,e,t'),
    nonsense('grintub', 'g,r,i,n,t,u,b'),
    nonsense('prendik', 'p,r,e,n,d,i,k'),
    nonsense('skanlot', 's,k,a,n,l,o,t'),
    nonsense('twindop', 't,w,i,n,d,o,p'),
  ],
  sentences: [
    'Sam has a fat pumpkin.',
    'Pam has a little pumpkin.',
    'The children have a contest.',
    'Dan has a problem with his van.',
    'The kid has a basket and a pumpkin.',
    'The pumpkin is over the wall.',
    'The other kid has the trumpet.',
    'Dan does a handstand on the mat.',
    'Sam has only one pretzel.',
    'Pam has a rabbit in the sandbox.',
    'Dan has sunblock at the picnic.',
    'The bandit ran from the contest.',
    'Sam has a kickstand on his wagon.',
    'The windsock is over the wall.',
    'The compost is in the sun.',
    'The drumstick fell in the mud.',
    'Pam has a pretzel and a muffin.',
    'Dan has a splendid handoff.',
  ],
  stories: [
    {
      title: 'The Pumpkin Contest',
      sentences: [
        'Sam has a fat pumpkin.',
        'Pam has a little pumpkin.',
        'The children have a contest.',
        'Sam and Pam sit on a big blanket.',
        'Sam has a problem with his fat pumpkin.',
        'It can not sit on the blanket.',
        'The little pumpkin is on the blanket.',
        'Sam and Pam have fun at the contest.',
      ],
      questions: [
        { prompt: 'Who has a fat pumpkin?', choices: ['Sam', 'Pam', 'the children'], answer: 0 },
        {
          prompt: 'Which pumpkin sits on the blanket?',
          choices: ['the little pumpkin', 'the fat pumpkin', 'the blanket'],
          answer: 0,
        },
      ],
    },
    {
      title: 'The Dentist and the Pretzel',
      sentences: [
        'Dan was at the dentist with a pretzel.',
        'The pretzel fell in the mud.',
        'Dan was upset and frantic.',
        'The dentist said it was not a big problem.',
        'A splendid pretzel was in his basket.',
        'The splendid pretzel was for Dan.',
        'Dan sat in the sun with it.',
      ],
      questions: [
        {
          prompt: 'What happened to the first pretzel?',
          choices: ['it fell in the mud', 'it was in the basket', 'it was in the sun'],
          answer: 0,
        },
        { prompt: 'Who was upset and frantic?', choices: ['Dan', 'the dentist', 'the pretzel'], answer: 0 },
      ],
    },
    {
      title: 'The Softball Contest',
      sentences: [
        'Sam and Dan have a softball contest.',
        'Dan has sunblock in the sun.',
        'Sam has a big hit, and the ball is up in the sun.',
        'The ball fell in the sandbox.',
        'Dan ran to the sandbox for the ball.',
        'Dan has the ball, and the contest is over.',
        'Sam has a splendid hit, and Dan has the ball.',
      ],
      questions: [
        { prompt: 'Where did the ball fall?', choices: ['in the sandbox', 'at the contest', 'in the sun'], answer: 0 },
        { prompt: 'Who ran to get the ball?', choices: ['Dan', 'Sam', 'the sandbox'], answer: 0 },
        {
          prompt: 'Who has the ball at the end of the story?',
          choices: ['Dan', 'Sam', 'the softball contest'],
          answer: 0,
        },
      ],
    },
    {
      title: 'The Drumstick Contest',
      sentences: [
        'Sam and Dan have a drumstick contest.',
        'Dan has a backdrop in the sun.',
        'The drumstick fell in the mud.',
        'Dan is upset.',
        'Dan has a lunchbox in the sun.',
        'The lunchbox has a drumstick in it.',
        'Dan has the drumstick, and the contest is over.',
      ],
      questions: [
        { prompt: 'Where did the drumstick fall?', choices: ['in the mud', 'in the lunchbox', 'in the sun'], answer: 0 },
        { prompt: 'What was inside the lunchbox?', choices: ['a drumstick', 'a backdrop', 'mud'], answer: 0 },
        { prompt: 'Who has the drumstick at the end of the story?', choices: ['Dan', 'Sam', 'the backdrop'], answer: 0 },
      ],
    },
  ],
};
