import type { Substep } from '../types';
import { word, nonsense } from '../build';

export const SUBSTEP_3_2: Substep = {
  id: '3.2',
  title: 'Two syllables with blends',
  parentSummary:
    'Your child reads two-syllable words made of two closed syllables, where at least one syllable has a blend, two or more consonants said together, such as "problem" and "pumpkin". They keep tapping every sound in order, syllable by syllable, then swipe to blend each part and say the whole word.',
  groups: [
    {
      cards: [],
      lesson: [
        { say: 'Today some syllables have a blend too, two or more sounds squeezed together, and we still tap every sound.' },
        { show: ['p', 'r', 'o', 'b', 'l', 'e', 'm'] },
        { say: 'Problem has two syllables, prob and lem. The first syllable starts with the blend p and r together.' },
        { tap: 'problem' },
        { say: 'Your turn. Tap every sound in each syllable, then swipe to blend the whole word.' },
        { try: 'blanket' },
        { try: 'pumpkin' },
        { try: 'unplug' },
      ],
    },
  ],
  concepts: [],
  sightWords: ['little', 'over', 'only', 'other'],
  words: [
    // Real: two closed syllables, at least one with a blend
    word('problem', 'p,r,o,b,l,e,m', { syllables: [4] }),
    word('plastic', 'p,l,a,s,t,i,c', { syllables: [4] }),
    word('dentist', 'd,e,n,t,i,s,t', { syllables: [3] }),
    word('contest', 'c,o,n,t,e,s,t', { syllables: [3] }),
    word('children', 'ch,i,l,d,r,e,n', { syllables: [3] }),
    word('hundred', 'h,u,n,d,r,e,d', { syllables: [3] }),
    word('blanket', 'b,l,a,n,k,e,t', { syllables: [4] }),
    word('trumpet', 't,r,u,m,p,e,t', { syllables: [4] }),
    word('pumpkin', 'p,u,m,p,k,i,n', { syllables: [4] }),

    word('address', 'a,d,d,r,e,ss:s', { syllables: [2] }),
    word('unplug', 'u,n,p,l,u,g', { syllables: [2] }),
    word('command', 'c,o,m,m,a,n,d', { syllables: [3] }),
    word('invent', 'i,n,v,e,n,t', { syllables: [2] }),
    word('sandwich', 's,a,n,d,w,i,ch', { syllables: [4] }),
    word('dustpan', 'd,u,s,t,p,an', { syllables: [4] }),
    word('handstand', 'h,a,n,d,s,t,a,n,d', { syllables: [4] }),
    word('frantic', 'f,r,a,n,t,i,c', { syllables: [4] }),
    word('splendid', 's,p,l,e,n,d,i,d', { syllables: [5] }),
    word('pretzel', 'p,r,e,t,z,e,l', { syllables: [4] }),
    word('instant', 'i,n,s,t,a,n,t', { syllables: [2] }),
    word('expand', 'e,x,p,a,n,d', { syllables: [2] }),
    word('impress', 'i,m,p,r,e,ss:s', { syllables: [2] }),
    word('handoff', 'h,a,n,d,o,ff:f', { syllables: [4] }),
    word('windmill', 'w,i,n,d,m,i,ll:l', { syllables: [4] }),
    word('sandbox', 's,a,n,d,b,o,x', { syllables: [4] }),
    word('extend', 'e,x,t,e,n,d', { syllables: [2] }),

    word('softball', 's,o,f,t,b,all', { syllables: [4] }),

    // More real words in the same shape, added so the section has enough to read.
    word('sunblock', 's,u,n,b,l,o,ck', { syllables: [3] }),
    word('drumstick', 'd,r,u,m,s,t,i,ck', { syllables: [4] }),
    word('handbag', 'h,a,n,d,b,a,g', { syllables: [4] }),
    word('lipstick', 'l,i,p,s,t,i,ck', { syllables: [3] }),
    word('kickstand', 'k,i,ck,s,t,a,n,d', { syllables: [3] }),
    word('windsock', 'w,i,n,d,s,o,ck', { syllables: [4] }),
    word('lunchbox', 'l,u,n,ch,b,o,x', { syllables: [4] }),
    word('backdrop', 'b,a,ck,d,r,o,p', { syllables: [3] }),

    // Nonsense: same two-closed-syllable shape, always with a blend
    nonsense('clantof', 'c,l,a,n,t,o,f'),
    nonsense('flondep', 'f,l,o,n,d,e,p'),
    nonsense('dranlop', 'd,r,a,n,l,o,p'),
    nonsense('flistub', 'f,l,i,s,t,u,b'),
    nonsense('frandup', 'f,r,a,n,d,u,p'),
    nonsense('plomkin', 'p,l,o,m,k,i,n'),
    nonsense('scaltop', 's,c,a,l,t,o,p'),
    nonsense('trubmit', 't,r,u,b,m,i,t'),
    nonsense('vindrest', 'v,i,n,d,r,e,s,t'),
    nonsense('wispram', 'w,i,s,p,r,am'),
    nonsense('stubnet', 's,t,u,b,n,e,t'),
    nonsense('clundip', 'c,l,u,n,d,i,p'),
    nonsense('brantip', 'b,r,a,n,t,i,p'),
    nonsense('clempot', 'c,l,e,m,p,o,t'),
    nonsense('drenlip', 'd,r,e,n,l,i,p'),
    nonsense('flampet', 'f,l,a,m,p,e,t'),
    nonsense('grintub', 'g,r,i,n,t,u,b'),
    nonsense('grustep', 'g,r,u,s,t,e,p'),
    nonsense('trenlug', 't,r,e,n,l,u,g'),
    nonsense('twindop', 't,w,i,n,d,o,p'),
  ],
  sentences: [
    'Sam has a fat pumpkin.',
    'Pam has a little pumpkin.',
    'The children have a contest.',
    'Dan has a problem with his van.',
    'The kid has a basket and a pumpkin.',
    'The pumpkin is over the wall.',
    'The other kid has the trumpet.',
    'Dan does a handstand on the mat.',
    'Sam has only one pretzel.',
    'A rabbit ran in the sandbox.',
    'Dan had sunblock on his neck at the picnic.',
    'Pam got the dustpan from the shed.',
    'Sam can fix the kickstand on his wagon.',
    'Dan put the windsock up on the shed.',
    'The lipstick was in the handbag.',
    'The drumstick fell in the mud.',
    'Pam has a pretzel and a muffin.',
    'The children ran to Dan for the handoff.',
  ],
  stories: [
    {
      title: 'The Pumpkin Contest',
      sentences: [
        'Sam has a fat pumpkin.',
        'Pam has a little pumpkin.',
        'The children have a contest.',
        'Sam and Pam sit on a big blanket.',
        'Sam has a problem with his fat pumpkin.',
        'It can not sit on the blanket.',
        'The little pumpkin is on the blanket.',
        'Sam can hold the fat pumpkin on his lap.',
        'The fat pumpkin is the best, and the contest is over.',
      ],
      questions: [
        { prompt: 'Who has a fat pumpkin?', choices: ['Sam', 'Pam', 'the children'], answer: 0 },
        {
          prompt: 'Which pumpkin sits on the blanket?',
          choices: ['the little pumpkin', 'the fat pumpkin', 'the blanket'],
          answer: 0,
        },
        {
          prompt: 'At the end, which pumpkin is the best?',
          choices: ['the fat pumpkin', 'the little pumpkin', 'the big blanket'],
          answer: 0,
        },
      ],
    },
    {
      title: 'The Dentist and the Pretzel',
      sentences: [
        'Dan went to the dentist with a pretzel.',
        'On the path, the pretzel fell in the mud.',
        'Dan was upset and frantic.',
        'The dentist said it was not a big problem.',
        'A splendid pretzel was in his basket.',
        'The splendid pretzel was for Dan.',
        'Dan sat in the sun with it.',
      ],
      questions: [
        {
          prompt: 'What happened to the first pretzel?',
          choices: ['it fell in the mud', 'it was in the basket', 'it was in the sun'],
          answer: 0,
        },
        { prompt: 'Who was upset and frantic?', choices: ['Dan', 'the dentist', 'the pretzel'], answer: 0 },
      ],
    },
    {
      title: 'The Ball in the Sandbox',
      sentences: [
        'At the picnic, Sam and Dan went to the sandbox with a softball.',
        'The sun was hot, and Dan had sunblock on his neck.',
        'Sam hit the ball, and it went up in the sun.',
        'The ball fell in the sandbox with a thud.',
        'Dan ran to the sandbox, but the ball was in the sand.',
        'Sam and Dan put a hand in the sand and did not stop.',
        'Dan got the ball, and Sam got sand in his socks.',
        'Sam and Dan went back to the picnic with the ball.',
      ],
      questions: [
        {
          prompt: 'Where did the ball fall?',
          choices: ['in the sandbox', 'on his neck', 'in his socks'],
          answer: 0,
        },
        { prompt: 'What did Dan have on his neck?', choices: ['sunblock', 'sand', 'the softball'], answer: 0 },
        {
          prompt: 'What did Sam and Dan do at the end of the story?',
          choices: ['went back to the picnic', 'put a hand in the sand', 'hit the ball'],
          answer: 0,
        },
      ],
    },
    {
      title: 'The Drumstick in the Mud',
      sentences: [
        'Pam and Dan went to the shed to do a song.',
        'Pam got the trumpet, and Dan got his drumstick.',
        'Dan ran in the mud, and the drumstick fell from his hand.',
        'Dan was upset and frantic.',
        'Pam went back to the shed and got a rag and a dustpan.',
        'Dan put the drumstick in the dustpan, and Pam got the mud off it with the rag.',
        'Then Pam and Dan did the song, and it was a big hit.',
      ],
      questions: [
        {
          prompt: 'Where did the drumstick fall?',
          choices: ['in the mud', 'in the shed', 'on the trumpet'],
          answer: 0,
        },
        { prompt: 'What did Pam use to get the mud off?', choices: ['the rag', 'the trumpet', 'the song'], answer: 0 },
        {
          prompt: 'How does the story end?',
          choices: ['Pam and Dan did the song', 'the drumstick fell in the mud', 'Dan was upset and frantic'],
          answer: 0,
        },
      ],
    },
  ],
};
