import type { Substep } from '../types';
import { word, nonsense } from '../build';

export const SUBSTEP_3_4: Substep = {
  id: '3.4',
  title: 'Three or more syllables',
  parentSummary:
    'Your child learns to break big words into three or more small chunks, each one a short closed syllable that ends in a consonant sound. Words like "fantastic" and "disconnect" are read one chunk at a time: fan-tas-tic, dis-con-nect.',
  groups: [
    {
      cards: [],
      lesson: [
        { say: 'Some words look huge, but they are still just chunks put together, two or three or more.' },
        { show: ['b', 'a', 's', 'k', 'e', 't', 'b', 'all'] },
        { say: 'Say each chunk by itself, then blend the chunks together to say the whole word.' },
        { tap: 'basketball' },
        { say: 'Your turn. Break the word into its chunks, then blend them together.' },
        { try: 'fantastic' },
        { try: 'establish' },
        { try: 'disconnect' },
      ],
    },
  ],
  concepts: ['multisyllable'],
  sightWords: ['know', 'through', 'where', 'here'],
  words: [
    // Real words: three or more closed syllables.
    word('basketball', 'b,a,s,k,e,t,b,all', { syllables: [3, 6] }),
    word('establish', 'e,s,t,a,b,l,i,sh', { syllables: [2, 5] }),
    word('disconnect', 'd,i,s,c,o,n,n,e,c,t', { syllables: [3, 6] }),
    word('fantastic', 'f,a,n,t,a,s,t,i,c', { syllables: [3, 6] }),
    word('Atlantic', 'a,t,l,a,n,t,i,c', { syllables: [2, 5] }),
    word('disrespect', 'd,i,s,r,e,s,p,e,c,t', { syllables: [3, 6] }),
    word('subcontract', 's,u,b,c,o,n,t,r,a,c,t', { syllables: [3, 6] }),
    word('inhabit', 'i,n,h,a,b,i,t', { syllables: [2, 5] }),
    word('uncommon', 'u,n,c,o,m,m,o,n', { syllables: [2, 5] }),
    word('unselfish', 'u,n,s,e,l,f,i,sh', { syllables: [2, 6] }),
    word('disinfect', 'd,i,s,i,n,f,e,c,t', { syllables: [3, 5] }),
    word('contradict', 'c,o,n,t,r,a,d,i,c,t', { syllables: [3, 7] }),
    word('badminton', 'b,a,d,m,i,n,t,o,n', { syllables: [3, 6] }),
    word('Wisconsin', 'w,i,s,c,o,n,s,i,n', { syllables: [3, 6] }),
    word('Manhattan', 'm,a,n,h,a,t,t,an', { syllables: [3, 6] }),
    word('indistinct', 'i,n,d,i,s,t,i,n,c,t', { syllables: [2, 5] }),
    word('adjustment', 'a,d,j,u,s,t,m,e,n,t', { syllables: [2, 6] }),
    word('punishment', 'p,u,n,i,sh,m,e,n,t', { syllables: [3, 5] }),
    word('compliment', 'c,o,m,p,l,i,m,e,n,t', { syllables: [3, 7] }),
    word('instrument', 'i,n,s,t,r,u,m,e,n,t', { syllables: [2, 7] }),
    word('refreshment', 'r,e,f,r,e,sh,m,e,n,t', { syllables: [3, 6] }),
    word('attachments', 'a,t,t,a,ch,m,e,n,t,s', { syllables: [2, 5] }),
    word('insistent', 'i,n,s,i,s,t,e,n,t', { syllables: [2, 6] }),
    word('contestant', 'c,o,n,t,e,s,t,a,n,t', { syllables: [3, 7] }),
    word('lunchboxes', 'l,u,n,ch,b,o,x,e,s', { syllables: [4, 7] }),
    word('establishment', 'e,s,t,a,b,l,i,sh,m,e,n,t', { syllables: [2, 5, 8] }),

    // More three-or-more-syllable words, still built only from sounds taught so far.
    word('consonant', 'c,o,n,s,o,n,a,n,t', { syllables: [3, 6] }),
    word('consonants', 'c,o,n,s,o,n,a,n,t,s', { syllables: [3, 6] }),
    word('chickenpox', 'ch,i,ck,e,n,p,o,x', { syllables: [3, 5] }),
    word('sandwiches', 's,a,n,d,w,i,ch,e,s', { syllables: [4, 7] }),
    word('sandboxes', 's,a,n,d,b,o,x,e,s', { syllables: [4, 7] }),
    word('accomplish', 'a,c,c,o,m,p,l,i,sh', { syllables: [2, 5] }),
    word('matchboxes', 'm,a,t,ch,b,o,x,e,s', { syllables: [4, 7] }),
    word('wristwatches', 'w,r,i,s,t,w,a,t,ch,e,s', { syllables: [5, 9] }),
    word('witnesses', 'w,i,t,n,e,ss:s,e,s', { syllables: [3, 6] }),

    // Nonsense: same three-syllable closed shapes.
    nonsense('vandriplum', 'v,a,n,d,r,i,p,l,u,m'),
    nonsense('distracmit', 'd,i,s,t,r,a,c,m,i,t'),
    nonsense('fantoblip', 'f,a,n,t,o,b,l,i,p'),
    nonsense('submandix', 's,u,b,m,a,n,d,i,x'),
    nonsense('conbastel', 'c,o,n,b,a,s,t,e,l'),
    nonsense('undrimpot', 'u,n,d,r,i,m,p,o,t'),
    nonsense('mislantic', 'm,i,s,l,a,n,t,i,c'),
    nonsense('trusvendum', 't,r,u,s,v,e,n,d,u,m'),
    nonsense('onbistrek', 'o,n,b,i,s,t,r,e,k'),
    nonsense('blimkastin', 'b,l,i,m,k,a,s,t,i,n'),
    nonsense('sunpelmit', 's,u,n,p,e,l,m,i,t'),
    nonsense('grandistop', 'g,r,a,n,d,i,s,t,o,p'),

    // More nonsense, same three-syllable closed shapes.
    nonsense('fantriplem', 'f,a,n,t,r,i,p,l,e,m'),
    nonsense('conshadrup', 'c,o,n,sh,a,d,r,u,p'),
    nonsense('distrunpock', 'd,i,s,t,r,u,n,p,o,ck'),
    nonsense('blenmafrosh', 'b,l,e,n,m,a,f,r,o,sh'),
    nonsense('wintroblun', 'w,i,n,t,r,o,b,l,u,n'),
    nonsense('sonclatrim', 's,o,n,c,l,a,t,r,i,m'),
    nonsense('hendrupmash', 'h,e,n,d,r,u,p,m,a,sh'),
    nonsense('vindraclosh', 'v,i,n,d,r,a,c,l,o,sh'),
  ],
  sentences: [
    'Sam has a fantastic basketball.',
    'The contestant is unselfish.',
    'Dan and Pam inhabit Wisconsin.',
    'They establish a badminton net here.',
    'The uncommon net does not disconnect.',
    'Sam does not know where Dan is.',
    'Pam and Sam run through the shed.',
    'Dan can establish a badminton net.',
    'Pam and Sam have fun in Manhattan.',
    'Sam will pack sandwiches in the lunchboxes.',
    'Dan has wristwatches and a compliment.',
    'Pam has matchboxes in a box.',
    'Dan will not disrespect Pam.',
    'Dan can accomplish this and that.',
    'This is a consonant.',
    'Sam and Dan know the consonants.',
    'Pam has a refreshment from the shop.',
    'Sam has an instrument in the shed.',
  ],
  stories: [
    {
      title: 'The Uncommon Basketball',
      sentences: [
        'Sam has a fantastic basketball.',
        'Sam and Dan sit in the sun in Manhattan.',
        'Sam and Dan do not know where the basketball is.',
        'They know the basketball is uncommon.',
        'Pam has the basketball in the shed.',
        'Sam and Dan run to the shed.',
        'Sam has the basketball, and Dan is not sad.',
      ],
      questions: [
        { prompt: 'Where is the basketball?', choices: ['in the shed', 'in Manhattan', 'in the sun'], answer: 0 },
        { prompt: 'What is uncommon?', choices: ['the basketball', 'the shed', 'Manhattan'], answer: 0 },
      ],
    },
    {
      title: 'Badminton in Wisconsin',
      sentences: [
        'Pam and Sam inhabit Wisconsin.',
        'They establish a badminton net here.',
        'The net is uncommon and does not disconnect.',
        'Dan does not have a net.',
        'Sam is unselfish, and Dan can have the net.',
        'Dan and Sam run to the badminton net.',
        'Dan has the net, and Sam is not mad.',
      ],
      questions: [
        { prompt: 'What does not disconnect?', choices: ['the net', 'Wisconsin', 'Dan'], answer: 0 },
        { prompt: 'Who is unselfish with the net?', choices: ['Sam', 'Pam', 'Dan'], answer: 0 },
      ],
    },
    {
      title: 'The Lunchboxes and the Sandboxes',
      sentences: [
        'Sam and Dan have lunchboxes with sandwiches.',
        'They sit in the sandboxes with the lunchboxes.',
        'Dan will mix up the lunchboxes.',
        'Sam does not know which box has the sandwiches.',
        'Pam has the box with the sandwiches.',
        'Sam is not sad.',
        'The box has fantastic sandwiches.',
      ],
      questions: [
        { prompt: 'What did Dan mix up?', choices: ['the lunchboxes', 'the sandboxes', 'the sandwiches'], answer: 0 },
        { prompt: 'Who has the box with the sandwiches at the end?', choices: ['Pam', 'Sam', 'Dan'], answer: 0 },
      ],
    },
    {
      title: 'Dan Has Chickenpox',
      sentences: [
        'Dan has chickenpox.',
        'Dan is sad, and he does not run.',
        'Jan has wristwatches and a compliment for Dan.',
        'Jan said Dan will not miss the fun.',
        'Dan has a refreshment from Jan.',
        'Dan is not sad, and he is not mad.',
        'He does not miss the fun.',
      ],
      questions: [
        { prompt: 'What does Dan have at the start of the story?', choices: ['chickenpox', 'a wristwatch', 'a refreshment'], answer: 0 },
        { prompt: 'How does Dan feel at the end of the story?', choices: ['not sad', 'sad', 'mad'], answer: 0 },
      ],
    },
  ],
};
