import type { Substep } from '../types';
import { word, nonsense } from '../build';

export const SUBSTEP_3_4: Substep = {
  id: '3.4',
  title: 'Three or more syllables',
  parentSummary:
    'Your child learns to break big words into three or more small chunks, each one a short closed syllable that ends in a consonant sound. Words like "fantastic" and "disconnect" are read one chunk at a time: fan-tas-tic, dis-con-nect.',
  groups: [
    {
      cards: [],
      lesson: [
        { say: 'Some words look huge, but they are still just chunks put together, two or three or more.' },
        { show: ['b', 'a', 's', 'k', 'e', 't', 'b', 'all'] },
        { say: 'Say each chunk by itself, then blend the chunks together to say the whole word.' },
        { tap: 'basketball' },
        { say: 'Your turn. Break the word into its chunks, then blend them together.' },
        { try: 'fantastic' },
        { try: 'establish' },
        { try: 'disconnect' },
      ],
    },
  ],
  concepts: ['multisyllable'],
  sightWords: ['know', 'through', 'where', 'here'],
  words: [
    // Real words: three or more closed syllables.
    word('basketball', 'b,a,s,k,e,t,b,all', { syllables: [3, 6] }),
    word('establish', 'e,s,t,a,b,l,i,sh', { syllables: [2, 5] }),
    word('disconnect', 'd,i,s,c,o,n,n,e,c,t', { syllables: [3, 6] }),
    word('fantastic', 'f,a,n,t,a,s,t,i,c', { syllables: [3, 6] }),
    word('atlantic', 'a,t,l,a,n,t,i,c', { syllables: [2, 5] }),
    word('misconduct', 'm,i,s,c,o,n,d,u,c,t', { syllables: [3, 6] }),
    word('subcontract', 's,u,b,c,o,n,t,r,a,c,t', { syllables: [3, 6] }),
    word('inhabit', 'i,n,h,a,b,i,t', { syllables: [2, 5] }),
    word('uncommon', 'u,n,c,o,m,m,o,n', { syllables: [2, 5] }),
    word('unselfish', 'u,n,s,e,l,f,i,sh', { syllables: [2, 6] }),
    word('disinfect', 'd,i,s,i,n,f,e,c,t', { syllables: [3, 5] }),
    word('contradict', 'c,o,n,t,r,a,d,i,c,t', { syllables: [3, 7] }),
    word('badminton', 'b,a,d,m,i,n,t,o,n', { syllables: [3, 6] }),
    word('wisconsin', 'w,i,s,c,o,n,s,i,n', { syllables: [3, 6] }),
    word('manhattan', 'm,a,n,h,a,t,t,an', { syllables: [3, 6] }),
    word('indistinct', 'i,n,d,i,s,t,i,n,c,t', { syllables: [2, 5] }),
    word('adjustment', 'a,d,j,u,s,t,m,e,n,t', { syllables: [2, 6] }),
    word('punishment', 'p,u,n,i,sh,m,e,n,t', { syllables: [3, 5] }),
    word('investment', 'i,n,v,e,s,t,m,e,n,t', { syllables: [2, 6] }),
    word('enlistment', 'e,n,l,i,s,t,m,e,n,t', { syllables: [2, 6] }),
    word('commitment', 'c,o,m,m,i,t,m,e,n,t', { syllables: [3, 6] }),
    word('consultant', 'c,o,n,s,u,l,t,a,n,t', { syllables: [3, 7] }),
    word('insistent', 'i,n,s,i,s,t,e,n,t', { syllables: [2, 6] }),
    word('contestant', 'c,o,n,t,e,s,t,a,n,t', { syllables: [3, 7] }),
    word('combatant', 'c,o,m,b,a,t,a,n,t', { syllables: [3, 6] }),
    word('establishment', 'e,s,t,a,b,l,i,sh,m,e,n,t', { syllables: [2, 5, 8] }),

    // Nonsense: same three-syllable closed shapes.
    nonsense('vandriplum', 'v,a,n,d,r,i,p,l,u,m'),
    nonsense('distracmit', 'd,i,s,t,r,a,c,m,i,t'),
    nonsense('fantoblip', 'f,a,n,t,o,b,l,i,p'),
    nonsense('submandix', 's,u,b,m,a,n,d,i,x'),
    nonsense('conbastel', 'c,o,n,b,a,s,t,e,l'),
    nonsense('undrimpot', 'u,n,d,r,i,m,p,o,t'),
    nonsense('mislantic', 'm,i,s,l,a,n,t,i,c'),
    nonsense('trusvendum', 't,r,u,s,v,e,n,d,u,m'),
    nonsense('onbistrek', 'o,n,b,i,s,t,r,e,k'),
    nonsense('blimkastin', 'b,l,i,m,k,a,s,t,i,n'),
    nonsense('sunpelmit', 's,u,n,p,e,l,m,i,t'),
    nonsense('grandistop', 'g,r,a,n,d,i,s,t,o,p'),
  ],
  sentences: [
    'Sam has a fantastic basketball.',
    'The contestant is unselfish.',
    'Dan and Pam inhabit Wisconsin.',
    'They establish a badminton net here.',
    'The uncommon net does not disconnect.',
    'Sam does not know where Dan is.',
    'Pam and Sam run through the shed.',
    'Dan can establish a badminton net.',
    'Pam and Sam have fun in Manhattan.',
  ],
  stories: [
    {
      title: 'The Uncommon Basketball',
      sentences: [
        'Sam has a fantastic basketball.',
        'Sam and Dan sit in the sun in Manhattan.',
        'Sam does not know where the basketball is.',
        'Dan does not know where it is.',
        'They know the basketball is uncommon.',
        'Pam has the basketball in the shed.',
        'Sam and Dan run to the shed.',
        'They have fun with the basketball in the shed.',
      ],
      questions: [
        { prompt: 'Where is the basketball?', choices: ['in the shed', 'in Manhattan', 'in the sun'], answer: 0 },
        { prompt: 'What is uncommon?', choices: ['the basketball', 'the shed', 'Manhattan'], answer: 0 },
      ],
    },
    {
      title: 'Badminton in Wisconsin',
      sentences: [
        'Pam and Sam inhabit Wisconsin.',
        'Dan does not have a net.',
        'They have a badminton net here.',
        'Sam is unselfish with the net.',
        'Pam and Sam establish badminton in Wisconsin.',
        'The net is uncommon and does not disconnect.',
        'Sam and Pam run through the shed.',
        'Sam and Pam have fun with the net.',
      ],
      questions: [
        { prompt: 'Where do Pam and Sam inhabit?', choices: ['Wisconsin', 'the shed', 'the net'], answer: 0 },
        { prompt: 'Who is unselfish with the net?', choices: ['Sam', 'Pam', 'Dan'], answer: 0 },
      ],
    },
  ],
};
