import type { Substep } from '../types';
import { word, nonsense } from '../build';

export const SUBSTEP_3_4: Substep = {
  id: '3.4',
  title: 'Three or more syllables',
  parentSummary:
    'Your child learns to break big words into three or more small chunks, each one a short closed syllable that ends in a consonant sound. Words like "fantastic" and "disconnect" are read one chunk at a time: fan-tas-tic, dis-con-nect.',
  groups: [
    {
      cards: [],
      lesson: [
        { say: 'Some words look huge, but they are still just chunks put together, two or three or more.' },
        { show: ['b', 'a', 's', 'k', 'e', 't', 'b', 'all'] },
        { say: 'Say each chunk by itself, then blend the chunks together to say the whole word.' },
        { tap: 'basketball' },
        { say: 'Your turn. Break the word into its chunks, then blend them together.' },
        { try: 'fantastic' },
        { try: 'establish' },
        { try: 'disconnect' },
      ],
    },
  ],
  concepts: ['multisyllable'],
  sightWords: ['know', 'through', 'where', 'here'],
  words: [
    // Real words: three or more closed syllables.
    word('basketball', 'b,a,s,k,e,t,b,all', { syllables: [3, 6] }),
    word('establish', 'e,s,t,a,b,l,i,sh', { syllables: [2, 5] }),
    word('disconnect', 'd,i,s,c,o,n,n,e,c,t', { syllables: [3, 6] }),
    word('fantastic', 'f,a,n,t,a,s,t,i,c', { syllables: [3, 6] }),
    word('Atlantic', 'a,t,l,a,n,t,i,c', { syllables: [2, 5] }),
    word('disrespect', 'd,i,s,r,e,s,p,e,c,t', { syllables: [3, 6] }),
    word('subcontract', 's,u,b,c,o,n,t,r,a,c,t', { syllables: [3, 6] }),
    word('inhabit', 'i,n,h,a,b,i,t', { syllables: [2, 5] }),
    word('uncommon', 'u,n,c,o,m,m,o,n', { syllables: [2, 5] }),
    word('unselfish', 'u,n,s,e,l,f,i,sh', { syllables: [2, 6] }),
    word('disinfect', 'd,i,s,i,n,f,e,c,t', { syllables: [3, 5] }),
    word('contradict', 'c,o,n,t,r,a,d,i,c,t', { syllables: [3, 7] }),
    word('badminton', 'b,a,d,m,i,n,t,o,n', { syllables: [3, 6] }),
    word('Wisconsin', 'w,i,s,c,o,n,s,i,n', { syllables: [3, 6] }),
    word('Manhattan', 'm,a,n,h,a,t,t,an', { syllables: [3, 6] }),
    word('indistinct', 'i,n,d,i,s,t,i,n,c,t', { syllables: [2, 5] }),
    word('adjustment', 'a,d,j,u,s,t,m,e,n,t', { syllables: [2, 6] }),
    word('punishment', 'p,u,n,i,sh,m,e,n,t', { syllables: [3, 5] }),
    word('compliment', 'c,o,m,p,l,i,m,e,n,t', { syllables: [3, 7] }),
    word('instrument', 'i,n,s,t,r,u,m,e,n,t', { syllables: [2, 7] }),
    word('refreshment', 'r,e,f,r,e,sh,m,e,n,t', { syllables: [3, 6] }),
    word('insistent', 'i,n,s,i,s,t,e,n,t', { syllables: [2, 6] }),
    word('contestant', 'c,o,n,t,e,s,t,a,n,t', { syllables: [3, 7] }),
    word('lunchboxes', 'l,u,n,ch,b,o,x,e,s', { syllables: [4, 7] }),
    word('establishment', 'e,s,t,a,b,l,i,sh,m,e,n,t', { syllables: [2, 5, 8] }),

    // More three-or-more-syllable words, still built only from sounds taught so far.
    word('consonant', 'c,o,n,s,o,n,a,n,t', { syllables: [3, 6] }),
    word('consonants', 'c,o,n,s,o,n,a,n,t,s', { syllables: [3, 6] }),
    word('chickenpox', 'ch,i,ck,e,n,p,o,x', { syllables: [3, 5] }),
    word('sandwiches', 's,a,n,d,w,i,ch,e,s', { syllables: [4, 7] }),
    word('sandboxes', 's,a,n,d,b,o,x,e,s', { syllables: [4, 7] }),
    word('accomplish', 'a,c,c,o,m,p,l,i,sh', { syllables: [2, 5] }),
    word('witnesses', 'w,i,t,n,e,ss:s,e,s', { syllables: [3, 6] }),

    // Everyday compounds and long words a ten-year-old actually meets, each splitting
    // at a compound boundary or into plain closed chunks.
    word('cannonball', 'c,a,n,n,o,n,b,all', { syllables: [3, 6] }),
    word('sunglasses', 's,u,n,g,l,a,ss:s,e,s', { syllables: [3, 7] }),
    word('cactuses', 'c,a,c,t,u,s,e,s', { syllables: [3, 6] }),
    word('athletic', 'a,th,l,e,t,i,c', { syllables: [2, 5] }),
    word('athletics', 'a,th,l,e,t,i,c,s', { syllables: [2, 5] }),
    word('magnetic', 'm,a,g,n,e,t,i,c', { syllables: [3, 6] }),
    word('astonish', 'a,s,t,o,n,i,sh', { syllables: [2, 5] }),
    word('disinfectant', 'd,i,s,i,n,f,e,c,t,a,n,t', { syllables: [3, 5, 9] }),

    // Nonsense: same three-syllable closed shapes. Every one carries its syllables array, so the
    // child sees the same chunk boundaries she sees on the real words. No syllable boundary falls
    // inside a blend that English keeps together at the start of a syllable (pl, bl, dr, tr, cl),
    // because that would leave the chunk before it open — a syllable type Book 3 never teaches.
    { ...nonsense('vandisbelt', 'v,a,n,d,i,s,b,e,l,t'), syllables: [3, 6] },
    { ...nonsense('distracmit', 'd,i,s,t,r,a,c,m,i,t'), syllables: [3, 7] },
    { ...nonsense('fantesbulk', 'f,a,n,t,e,s,b,u,l,k'), syllables: [3, 6] },
    { ...nonsense('submandrop', 's,u,b,m,a,n,d,r,o,p'), syllables: [3, 6] },
    { ...nonsense('conbastel', 'c,o,n,b,a,s,t,e,l'), syllables: [3, 6] },
    { ...nonsense('undrimpot', 'u,n,d,r,i,m,p,o,t'), syllables: [2, 6] },
    { ...nonsense('mislantic', 'm,i,s,l,a,n,t,i,c'), syllables: [3, 6] },
    { ...nonsense('trusvendel', 't,r,u,s,v,e,n,d,e,l'), syllables: [4, 7] },
    { ...nonsense('onbistrek', 'o,n,b,i,s,t,r,e,k'), syllables: [2, 5] },
    { ...nonsense('blimkastin', 'b,l,i,m,k,a,s,t,i,n'), syllables: [4, 7] },
    { ...nonsense('sunpelmit', 's,u,n,p,e,l,m,i,t'), syllables: [3, 6] },
    { ...nonsense('grandistop', 'g,r,a,n,d,i,s,t,o,p'), syllables: [4, 7] },

    // More nonsense, same three-syllable closed shapes.
    { ...nonsense('belmastusk', 'b,e,l,m,a,s,t,u,s,k'), syllables: [3, 6] },
    { ...nonsense('conveldast', 'c,o,n,v,e,l,d,a,s,t'), syllables: [3, 6] },
    { ...nonsense('wintabdesk', 'w,i,n,t,a,b,d,e,s,k'), syllables: [3, 6] },
    { ...nonsense('sonmeldup', 's,o,n,m,e,l,d,u,p'), syllables: [3, 6] },
    { ...nonsense('hendrupmash', 'h,e,n,d,r,u,p,m,a,sh'), syllables: [3, 7] },
    { ...nonsense('vindaslend', 'v,i,n,d,a,s,l,e,n,d'), syllables: [3, 6] },
    { ...nonsense('veltansip', 'v,e,l,t,a,n,s,i,p'), syllables: [3, 6] },
    { ...nonsense('plundastek', 'p,l,u,n,d,a,s,t,e,k'), syllables: [4, 7] },
  ],
  sentences: [
    'Sam has a fantastic basketball.',
    'The contestant is unselfish.',
    'Dan and Pam inhabit Wisconsin.',
    'They establish a badminton net here.',
    'The uncommon net does not disconnect.',
    'Sam does not know where Dan is.',
    'Pam and Sam run through the shed.',
    'Sam is athletic, and he can run fast.',
    'The badminton contest is in Manhattan.',
    'Sam will pack sandwiches in the lunchboxes.',
    'Pam will pack the backpack and put it in the van.',
    'Dan got sunglasses at the shop.',
    'Dan will not disrespect Pam.',
    'Dan did accomplish the long run up the hill.',
    'Sam did not know which consonant to pick.',
    'Sam and Dan know the consonants.',
    'Pam has a refreshment from the shop.',
    'Sam has an instrument in the shed.',
    'Sam and Dan ran in the athletics contest.',
    'The cannonball fell into the pond.',
    'Dan will not sit on the cactuses.',
    'Dan put the box of mud in the shed.',
    'The magnetic lock on the box will not unlock.',
    'Pam will disinfect the cut with the disinfectant.',
    'It did astonish Dan that Pam had the basketball.',
  ],
  stories: [
    {
      title: 'The Uncommon Basketball',
      sentences: [
        'Sam and Dan sat on the path in the sun in Manhattan.',
        'Sam had a fantastic basketball, and it was uncommon.',
        'Sam hit the basketball, and it went into the shed.',
        'Sam and Dan ran to the shed, but they did not find the basketball.',
        'Sam was upset, and Dan did not know what to do.',
        'Then Pam went into the shed and got the basketball.',
        'Pam went to Sam with the basketball, and then Sam and Dan had a contest with it.',
      ],
      questions: [
        { prompt: 'Where did the basketball go when Sam hit it?', choices: ['into the shed', 'on the path', 'in the sun'], answer: 0 },
        { prompt: 'Who went into the shed and got the basketball?', choices: ['Pam', 'Sam', 'Dan'], answer: 0 },
        { prompt: 'What was uncommon?', choices: ['the basketball', 'the shed', 'the path'], answer: 0 },
      ],
    },
    {
      title: 'Badminton in Wisconsin',
      sentences: [
        'Pam and Sam went up a hill in Wisconsin.',
        'They had an uncommon badminton net that did not disconnect.',
        'Pam and Sam put up the net on the hill.',
        'Then Dan went up the hill, but Dan did not have a net.',
        'Dan was upset, and he sat down on the hill.',
        'Sam was unselfish, and Sam let Dan have the net.',
        'Dan and Sam had a badminton contest, and Pam said it was fantastic.',
      ],
      questions: [
        { prompt: 'What did not disconnect?', choices: ['the net', 'the hill', 'Wisconsin'], answer: 0 },
        { prompt: 'Who let Dan have the net?', choices: ['Sam', 'Pam', 'Dan'], answer: 0 },
      ],
    },
    {
      title: 'The Lunchboxes and the Sandboxes',
      sentences: [
        'Sam, Dan and Pam sat in the sandboxes with the lunchboxes.',
        'Sam had sandwiches, Dan had chips, and Pam had a muffin.',
        'Dan got up to run, and he did mix up the lunchboxes.',
        'Sam did not know which lunchbox had the sandwiches.',
        'Sam was upset, and Dan was upset.',
        'Pam went to the lunchboxes and got the sandwiches back to Sam.',
        'Dan got the chips back, and then they had the sandwiches, the chips and the muffin in the sun.',
      ],
      questions: [
        { prompt: 'What did Dan mix up?', choices: ['the lunchboxes', 'the sandboxes', 'the sandwiches'], answer: 0 },
        { prompt: 'Who sorted out the sandwiches?', choices: ['Pam', 'Sam', 'Dan'], answer: 0 },
        { prompt: 'What did Pam have in her lunchbox?', choices: ['a muffin', 'chips', 'sandwiches'], answer: 0 },
      ],
    },
    {
      title: 'Dan Had Chickenpox',
      sentences: [
        'Dan had chickenpox, and he had to sit in bed.',
        'Sam, Pam and Jan went up the hill to have a picnic.',
        'Dan was sad, and he did not want to be in bed.',
        'Then Jan ran back down the hill to Dan.',
        'Jan had a box with sandwiches, a muffin and sunglasses in it.',
        'Jan put the box on the bed, and Dan and Jan had the picnic in bed.',
        'Dan had the muffin and told Jan that this picnic was the best.',
      ],
      questions: [
        { prompt: 'What did Dan have at the start of the story?', choices: ['chickenpox', 'sunglasses', 'a muffin'], answer: 0 },
        { prompt: 'Who went back down the hill to Dan?', choices: ['Jan', 'Sam', 'Pam'], answer: 0 },
        { prompt: 'Where did Dan and Jan have the picnic?', choices: ['in bed', 'up the hill', 'in the box'], answer: 0 },
      ],
    },
  ],
};
